version: '3'
services:
  bot:
    build:
      context: .
    environment:
      - DB_URL=postgresql://postgres:2705@db:5432/Art
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2705
      POSTGRES_DB: Art
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
